stages:
  - build
  - test
  - release

variables:
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME

build:
  stage: build
  script:
    - docker-compose -f docker-compose.test.yml build

test:
  stage: test
  before_script:
    - docker-compose -f docker-compose.test.yml up -d db
    - sleep 30
    - docker-compose -f docker-compose.test.yml run --rm app rake db:create
  script:
    - docker-compose -f docker-compose.test.yml run --rm app rspec
  after_script:
    - docker-compose -f docker-compose.test.yml down

release:
  stage: release
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker tag ipsapp_app $CONTAINER_RELEASE_IMAGE
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CONTAINER_RELEASE_IMAGE
