stages:
  - build
  - test

build:
  stage: build
  script:
    - docker-compose build

test:
  stage: test
  script:
    - docker-compose run --rb web rake db:create
    - docker-compose run --rm web rspec

after_script:
  - docker-compose down
