version: "2"

networks:
  ips:
    driver: bridge

services:
  db:
    container_name: db
    image: postgres:9.4.5
    networks:
      - ips

  app:
    container_name: app:latest
    build: .
    networks:
      - ips
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgresql://postgres:@db/ips
    depends_on:
      - db
