version: "2"

networks:
  ips:
    driver: bridge

services:
  db:
    container_name: db
    image: postgres:9.4.5
    networks:
      - ips

  app:
    container_name: app
    build: .
    networks:
      - ips
    environment:
      DATABASE_URL: postgresql://postgres:@db/ips-development
      EMAIL_SENDER: noreply@innovativepricingsolutions.com
    depends_on:
      - db
