version: "2"

services:
  app:
    image: ips-app
    command: test
    environment:
      DATABASE_URL: postgresql://postgres:@db/ips-test

  wait_for:
    image: jwilder/dockerize
    command: dockerize -wait tcp://db:5432 -timeout 60s
    networks:
      - ipds
