development: &default
  adapter: postgresql
  username: postgres
  password:
  host: db
  database: ips_development
  encoding: unicode

test:
  <<: *default
  database: ips_test

production:
  <<: *default
  database: ips_production
